name: marketplace_app

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "5231:5010"
    environment:
      - NODE_ENV=production
      - MARKETPLACE_API_HOST=localhost
      - MARKETPLACE_API_PORT=5010
      - MONGO_URL=mongodb://admin:admin_password@mongodb:27017/marketplace_db?authSource=admin
      - REDIS_URL=redis://redis:6379
      - STORAGE_DIR=/data/storage
    volumes:
      - marketplace-storage:/data/storage
    depends_on:
      - mongodb
      - redis
    networks:
      - marketplace_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: marketplace-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=marketplace_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - marketplace_network
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    container_name: marketplace-redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    environment:
      REDIS_PASSWORD: redis_password
    user: redis
    volumes:
      - redis-data:/data
      - ./docker/configs/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - marketplace_network
    restart: unless-stopped

networks:
  marketplace_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  marketplace-storage:
